In [20]:
import numpy as np
from scipy  import stats
import scipy as sp

In [8]:
# デフォルトはreplace = Trueになっており、このような被りを許可した抽出の仕方を復元抽出という
np.random.choice(np.arange(1, 7), 10)
# Falseにした場合は、非復元抽出という
# np.random.choice(np.arange(1, 7), 6, replace=False)

array([4, 2, 6, 1, 4, 4, 3, 2, 5, 3])

In [9]:
# np.random.choiceでは、標本が等確率でサンプリングされる
# 抽出する確率を変更したかったらpオプションを指定する
# 4,5,6が多く出るように調節
p = np.array([1, 1,1,3,3,3])
p = p/np.sum(p)
np.random.choice(np.arange(1, 7), 10, p=p)

array([5, 5, 1, 5, 5, 5, 4, 4, 6, 5])

In [10]:
# 期待値1、標準偏差2の正規分布に従うデータを100個生成
x = np.random.normal(1, 2, 100)
x.mean()

0.9428910541873803

In [11]:
x.std()

2.1086374009012747

In [12]:
# |x - E[x]| <= sd(x)となるデータの割合
np.mean(np.abs(x - x.mean())<= np.std(x))

0.68

In [13]:
# |x - E[x]| <= 2*sd(x)となるデータの割合
np.mean(np.abs(x - x.mean())<= 2 *np.std(x))

0.95

In [16]:
np.sum(np.abs(x - x.mean())<= 2 *np.std(x)) / (np.abs(x - x.mean())<= 2 *np.std(x)).size

0.95

In [21]:
# scipyでstatsを利用する場合は直接importで指定してやる必要がある
stats.norm.ppf(0.7)

0.5244005127080407

In [22]:
stats.norm.ppf(0.7, loc = 1, scale=2)

2.0488010254160813

In [23]:
alpha = 0.05
stats.norm.ppf(1-alpha)

1.6448536269514722

In [24]:
from sklearn.datasets import load_iris

In [28]:
iris = load_iris()
iris.data.shape

(150, 4)

In [29]:
# np.covは引数に確率変数の転置行列を入れてやることで分散共分散行列を得られる
# 標本共分散と母集団の共分散は異なることを前提に押さえておく
np.cov(iris.data.T)

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [30]:
# 標本相関係数 相関係数行列(データ行列の転置を入れる)
np.corrcoef(iris.data.T)

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [32]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']